name: Update badges

on:
  schedule:
    # Runs at 0am UTC
    - cron: "43 22 * * *"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:       
          CREDLY_USER: efren-andres-mora # optional, but default will use the same from github
