  
name: Update badges

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  # schedule:
    # Runs at 2am UTC
    # cron: "0 2 * * *"
    # Runs at 12:00 on day-of-month 1
    # - cron: "0 12 1 * *"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags' 

jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: Badges - Readme
        # uses: pemtajo/badge-readme@main
        # uses: pemtajo/badge-readme@2.3.0
        uses: efrenmo/badge-readme@main        
        with:
          CREDLY_USER: efren-andres-mora
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BADGE_SIZE: 120
          NUMBER_LAST_BADGES: 24
