name: Update badges

on:
  schedule:
    # Runs at 0am UTC
    - cron: "57 23 * * *"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:       
          CREDLY_USER: efren-andres-mora # optional, but default will use the same from github
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          BADGE_SIZE: 100
          NUMBER_LAST_BADGES: 24
